Spring:
    Application:
        name: config-default
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    defer-datasource-initialization: true
